name: Build and publish faasd function

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # nodig om commando's te kunnen uitvoeren
      - name: Download and install faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      # vereist om Docker images te kunnen bouwen
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
            # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: vincentnys
          password: ${{ secrets.IMAGEPROCESSINGDOCKERHUBTOKEN }}
      - name: Login for faasd
        run: faas-cli login --gateway https://jaws2paws.com -u admin --password ${{ secrets.FAASD_PASSWORD }}
      - name: Build function only
        run: faas-cli up -f image-processing.yml --gateway https://jaws2paws.com
